bridges = []

[[instances]]
name = "holochain_photos"
id = "__holochain_photos"
dna_hash = "Qmf44Mr8V75kTAdHEnYbSr1br7rh5YVhmEPuHxysjgRmg5"
uri = "file:dist/holochain_photos.dna.json" 

[[UIs]]
name = "Holochain Photos"
id = "holochain_photos_ui"
uri = "dir:./gui" 

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__holochain_photos"