bridges = []

[[instances]]
name = "holochain_photos"
id = "__holochain_photos"
dna_hash = "QmeexZcXHNM9Yh6HV47FnN1FGnHN8Yb6uaUEi2i6MxySjH"
uri = "file:dist/holochain_photos.dna.json" 

[[UIs]]
name = "Holochain Photos"
id = "holochain_photos_ui"
uri = "dir:./gui" 

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__holochain_photos"